### ISSUE TITLE
Add to the documentation not to use with layout discovery overrides module

### ISSUE THREAD

**Issue by katrialesser** [Lullabot/custom_layouts#1]
Add clarification that this module is SIMILAR to the layout discover overrides module, but they shouldn't be used together. They both do the same thing.
https://www.drupal.org/project/layout_discovery_override

**Comment by deviantintegral** [comment]
Thanks for the suggestion. This module ended up only being used as an example and is not being maintained. We are going to close all issues and archive the repository. Feel free to create a project on drupal.org or use this code directly in your own projects following Drupal's GPL license.
