### ISSUE TITLE
When using a section title, it goes before regions and then the columns or regions don't display properly

### ISSUE THREAD

**Issue by katrialesser** [Lullabot/custom_layouts#2]
When using a section title, it goes before regions and then the columns or regions don't display properly.
For instance, if you add a section with 2 columns, and you name that section, the title goes to the left of the 2 columns, and then it shows 
[title] [column one]
[column two on its own line]

Rather than:
[title]
[column one][column two on same line]

![image](https://user-images.githubusercontent.com/12898896/57636179-e2e02d80-7565-11e9-9e92-562ebfdf5d39.png)

Is this correct behavior? It requires fixing with css for every time a section title is used, which seems to mean that none of the section layouts will work as described IF you use a section title, unless you fix it with css.
I think that the section title should have it's own space at the top/above the section regions so that the layout selected is displayed properly.
Perhaps I misunderstand how this section title can be used.

**Comment by deviantintegral** [comment]
Thanks for the question. This module ended up only being used as an example and is not being maintained. We are going to close all issues and archive the repository. Feel free to create a project on drupal.org or use this code directly in your own projects following Drupal's GPL license.
