### ISSUE TITLE
Couldn't install following the ReadMe

### ISSUE THREAD

**Issue by katrialesser** [Lullabot/custom_layouts#3]
About a month ago I tried out this module and had some difficulties. This is just an issue in case you want to fix the READMe process. Following the README process, I couldn't get this module to work. I had to add this module as a custom module in modules/custom as a git sumodule. 

The instruction to add `lullabot/custom_layouts.....` lines however it was into the package.json file and then do the composer require... line would never actually install the module or do anything that I could see. The module worked fine once I added it via git as a git submodule or just via git clone in modules/custom.

**Comment by deviantintegral** [comment]
Thanks for the question. This module ended up only being used as an example and is not being maintained. We are going to close all issues and archive the repository. Feel free to create a project on drupal.org or use this code directly in your own projects following Drupal's GPL license.
