### ISSUE TITLE
Incorrect template being used

### ISSUE THREAD

**Issue by girdzijauskas** [Lullabot/custom_layouts#4]
If you use the layout 'layout_onecol_100' within layout builder for a section, the template that is used is the one from layout_discovery.

This seems to be because the definition of the layout includes 
```
path: layouts/onecol 
template: layout--onecol
```

which is the exact same for the layout discovery. Once I've renamed the template and updated the layout definition in `custom_layouts.layouts.yml`, it started to work as expected.

Is this some kind of scoping / override not being picked up issue?

**Comment by deviantintegral** [comment]
Thanks for the question. This module ended up only being used as an example and is not being maintained. We are going to close all issues and archive the repository. Feel free to create a project on drupal.org or use this code directly in your own projects following Drupal's GPL license.
