### ISSUE TITLE
Issues don't seem to be addresses but here is feedback anyway - composer.json error

### ISSUE THREAD

**Issue by HeneryH** [Lullabot/custom_layouts#5]
I tried to edit my composer.json according to the instructions with and without a comma and they both fail when running the composer command

    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        } ,
        "lullabot/custom_layouts": {
            "type": "vcs",
            "url": "https://github.com/lullabot/custom_layouts.git",
            "no-api": true
        }
    ],

With the comma I get 
`  [Seld\JsonLint\ParsingException]               
  "./composer.json" does not contain valid JSON  
  Parse error on line 15:                        
  ..."        }        "lullabot/custom_lay...   
  --------------------^                          
  Expected one of: 'EOF', '}', ',', ']'          
                                          `

Without the comma I get
`  [Seld\JsonLint\ParsingException]               
  "./composer.json" does not contain valid JSON  
  Parse error on line 16:                        
  ...abot/custom_layouts": {            "typ     
  ----------------------^                        
  Expected one of: 'EOF', '}', ',', ']'          
                                        `

**Comment by dalemoore** [comment]
This issue is old, and so is this module, but exclude this bit: "lullabot/custom_layouts": It won't work still though because the module isn't updated for Drupal 9+. Better to just do your own roll of it as this is an internal tool for Lullabot. You can use it as an example for creating your own version.

**Comment by deviantintegral** [comment]
Thanks for the response. This module ended up only being used as an example and is not being maintained. We are going to close all issues and archive the repository. Feel free to create a project on drupal.org or use this code directly in your own projects following Drupal's GPL license.
